added documentation for getFileContent()
NebulousLabs/skynet-docs pull request #48
Opened 2021-01-08 18:25 UTC by dhelma

First commit to the Slate docs, adding documentation for `getFileContent()` since it could be important for some upcoming partnerships.

First PR for the Slate docs, so review carefully :)

2021-01-08 19:58 UTC, m-cat commented on source/v3-beta/includes/_browser-js-api.md
> +`data` | Data returned in the request body when doing a GET request for the skylink.
```suggestion
`data` | Data returned in the response body when doing a GET request for the skylink.
```

2021-01-08 20:01 UTC, m-cat commented on source/v3-beta/includes/_browser-js-api.md
> +  skyfile = await client.getFileContent(skylink);
It is more convenient to get the data like this so maybe we should showcase it:

```suggestion
  const { data } = await client.getFileContent(skylink);
```

2021-01-08 20:02 UTC, m-cat requested changes
Looks mostly good, thanks!

2021-01-12 16:22 UTC, dhelma commented
Should be good to go.

2021-01-13 12:20 UTC, m-cat approved these changes

2021-01-13 12:20 UTC, merged